      SUBROUTINE CHGRID(FX,X,NX,FY,Y,NY)
      DIMENSION FX(NX),X(NX),FY(NY),Y(NY)
C  PIECEWISE QUADRATIC INTERPOLATION FROM GRID X TO GRID Y,  BY
C  AITKEN'S DIVIDED DIFFERENCE SCHEME.   NX,NY ARE ARRAY DIMENSIONS?
C  NOTE THAT NY IS RESET IN CHGRID
      IY=1
      DO 2 IX=3,NX
1     IF(IY.GT.NY)GOTO 3
      YY=Y(IY)
      IF(YY.GT.X(IX))GOTO 2
      A1=X(IX-2)-YY
      A2=X(IX-1)-YY
      A3=X(IX)-YY
      A12=(FX(IX-2)*A2-FX(IX-1)*A1)/(X(IX-1)-X(IX-2))
      A13=(FX(IX-2)*A3-FX(IX)*A1)/(X(IX)-X(IX-2))
      FY(IY)=(A12*A3-A13*A2)/(X(IX)-X(IX-1))
      IF(IY.GT.NY)GOTO 3
      IY=IY+1
      GOTO 1
2     CONTINUE
3     NY=IY-1
      RETURN
      END
