      SUBROUTINE MAD(VMAD,RX,NGRID,RMT,NRR,NX,NR,RC,RK,ZM,N,AV)
      DIMENSION VMAD(NGRID,NR),RX(NGRID),RC(3,3),RK(3,N),ZM(N),
     + RMT(NR),NRR(NR),NX(NR)
      COMMON /WK/ G(3,3),VMM(5),FR(5),RA(3),GA(3)
      DATA PI,TEST/3.1415926536,1.0E-4/
      RAD(A1,A2,A3)=SQRT(A1*A1+A2*A2+A3*A3)
C  SUBROUTINE MAD CALCULATES THE SPHERICALLY AND SPATIALLY AVERAGED
C  FIELDS FROM A LATTICE OF POINT CHARGES, AND TABULATES THEM ON
C  A RADIAL MESH RX, ABOUT EACH ATOMIC TYPE IN THE UNIT CELL
C  ** NB THIS ROUTINE WORKS IN HARTREES, BUT CONVERTS TO RYDBERGS **
C  RC(I,J) = THE I'TH COORDINATE OF THE J'TH AXIS OF THE UNIT CELL
C  RK(I,J) = THE I'TH COORDINATE OF THE J'TH ATOM IN THE UNIT CELL
C  VMAD(J,IR) = THE J'TH TABULATED VALUE OF THE SPHERICALLY AVERAGED
C  POTENTIAL ABOUT A TYPE-IR ATOM
C  ZM(K)=CHARGE ON THE K'TH ATOM
C  RMT(IR) = MUFFIN-TIN RADIUS OF A TYPE-IR ATOM
C  NR = NUMBER OF INEQUIVALENT ATOMS IN THE CELL
C  AV = VOLUME OF UNIT CELL
C  G(I,J) = I'TH COORDINATE OF THE J'TH RECIPROCAL LATTICE VECTOR
C  VMM(IR) = THE INTEGRAL OF THE POTENTIAL ABOUT A TYPE-IR ATOM
C  OUT TO THE MUFFIN-TIN RADIUS
C
      DO 1 IR=1,NR
      FR(IR)=0.0
      DO 1 J=1,NGRID
1     VMAD(J,IR)=0.0
C  THE RECIPROCAL LATTICE IS DEFINED BY THREE VECTORS, G
      ATV=2.0*PI/AV
      G(1,1)=(RC(2,1)*RC(3,2)-RC(3,1)*RC(2,2))*ATV
      G(2,1)=(RC(3,1)*RC(1,2)-RC(1,1)*RC(3,2))*ATV
      G(3,1)=(RC(1,1)*RC(2,2)-RC(2,1)*RC(1,2))*ATV
C
      G(1,2)=(RC(2,2)*RC(3,3)-RC(3,2)*RC(2,3))*ATV
      G(2,2)=(RC(3,2)*RC(1,3)-RC(1,2)*RC(3,3))*ATV
      G(3,2)=(RC(1,2)*RC(2,3)-RC(2,2)*RC(1,3))*ATV
C
      G(1,3)=(RC(2,3)*RC(3,1)-RC(3,3)*RC(2,1))*ATV
      G(2,3)=(RC(3,3)*RC(1,1)-RC(1,3)*RC(3,1))*ATV
      G(3,3)=(RC(1,3)*RC(2,1)-RC(2,3)*RC(1,1))*ATV
C
C  MAXIMUM VALUE OF RK, AND MINIMUM VALUES OF RC,G - PRIOR TO
C  CHOOSING THE SEPARATION CONSTANT AL AND LIMITS FOR
C  SUMMATIONS
      RKMAX=0.0
      DO 2 J=1,N
2     RKMAX=AMAX1(RKMAX,RAD(RK(1,J),RK(2,J),RK(3,J)))
      RCMIN=1.0E6
      GMIN=1.0E6
      DO 3 J=1,3
      RCMIN=AMIN1(RCMIN,RAD(RC(1,J),RC(2,J),RC(3,J)))
3     GMIN=AMIN1(GMIN,RAD(G(1,J),G(2,J),G(3,J)))
C  AL IS CHOSEN TO GIVE EQUAL NUMBERS OF TERMS IN REAL AND
C  RECIPROCAL SPACE SUMMATIONS
      FAC1=TEST*ALOG(TEST)**4
      FAC2=(4.0*PI*RCMIN**4)/(AV*GMIN**4)
      AL=EXP(ALOG(FAC1/FAC2)/6.0)
      ITR=1+IFIX((AL*RKMAX-ALOG(TEST))/(AL*RCMIN))
      LIMR=ITR+ITR+1
      FAC1=4.0*PI*AL*AL/(AV*GMIN**4)
      ITG=1+IFIX(EXP(ALOG(FAC1/TEST)/4.0))
      LIMG=ITG+ITG+1
      WRITE(11,200)((G(I,J),I=1,3),J=1,3)
      WRITE(11,201)RCMIN,GMIN,RKMAX,TEST,AL
C
C  REAL SPACE SUMMATION
      WRITE(11,202)ITR
C  THE PREFACTORS FR FROM THE REAL SPACE SUMMATION ARE CALCULATED
      AS=-FLOAT(ITR)-1.0
      AX=AS
      DO 5 JX=1,LIMR
      AX=AX+1.0
      AY=AS
      DO 5 JY=1,LIMR
      AY=AY+1.0
      AZ=AS
      DO 5 JZ=1,LIMR
      AZ=AZ+1.0
      DO 4 I=1,3
4     RA(I)=AX*RC(I,1)+AY*RC(I,2)+AZ*RC(I,3)
      DO 5 J=1,N
      K=1
      DO 5 KR=1,NR
      R=RAD(RA(1)+RK(1,J)-RK(1,K),RA(2)+RK(2,J)-RK(2,K),
     + RA(3)+RK(3,J)-RK(3,K))
      IF(R.LT.1.0E-4)GOTO 5
      FR(KR)=FR(KR)+ZM(J)*EXP(-AL*R)/R
5     K=K+NRR(KR)
      K=1
      DO 7 KR=1,NR
      X=RMT(KR)
      A=EXP(-AL*X)
      AI1=((1.0-A)/AL-X*A)/AL
      AI2=(X*0.5*(1.0/A+A)-0.5*(1.0/A-A)/AL)/AL/AL
      VMM(KR)=4.0*PI*(ZM(K)*AI1+AI2*FR(KR))
      NIX=NX(KR)
      DO 6 J=1,NIX
      X=RX(J)
      A=EXP(AL*X)
6     VMAD(J,KR)=FR(KR)*0.5*(A-1.0/A)/(AL*X)+ZM(K)/(A*X)
7     K=K+NRR(KR)
      WRITE(11,203)(VMM(KR),KR=1,NR)
C
C  NEXT COMES THE SUMMATION IN RECIPROCAL SPACE
      WRITE(11,204)ITG
      AS=-FLOAT(ITG)-1.0
      AX=AS
      DO 13 JX=1,LIMG
      AX=AX+1.0
      AY=AS
      DO 13 JY=1,LIMG
      AY=AY+1.0
      AZ=AS
      DO 13 JZ=1,LIMG
      AZ=AZ+1.0
      DO 8 I=1,3
8     GA(I)=AX*G(I,1)+AY*G(I,2)+AZ*G(I,3)
      GM=RAD(GA(1),GA(2),GA(3))
      GS=GM*GM
      FAC1=0.0
      IF(GS.LT.1.0E-4)GOTO 13
      FAC1=4.0*PI*AL*AL/(AV*GS*(GS+AL*AL))
      K=1
      DO 12 KR=1,NR
      FAC2=0.0
      DO 10 J=1,N
      GR=0.0
      DO 9 I=1,3
9     GR=GR+GA(I)*(RK(I,K)-RK(I,J))
10    FAC2=FAC2+COS(GR)*ZM(J)
      X=RMT(KR)
      AI3=(SIN(GM*X)/GM-X*COS(GM*X))/GS
      VMM(KR)=VMM(KR)+4.0*PI*AI3*FAC1*FAC2
      NIX=NX(KR)
      DO 11 I=1,NIX
      X=RX(I)
11    VMAD(I,KR)=VMAD(I,KR)+FAC1*FAC2*SIN(GM*X)/(GM*X)
12    K=K+NRR(KR)
13    CONTINUE
      WRITE(11,203)(VMM(KR),KR=1,NR)
C  REFER TO MUFFIN-TIN ZERO
      VM=0.0
      AMT=0.0
      DO 14 IR=1,NR
      VM=VM+FLOAT(NRR(IR))*RMT(IR)**3
14    AMT=AMT+FLOAT(NRR(IR))*VMM(IR)
      AMT=AMT/(AV-4.0*PI*VM/3.0)
C  EXPRESS THE FINAL POTENTIAL IN RYDBERGS
      AMT=-2.0*AMT
      WRITE(11,205)AMT
      DO 15 KR=1,NR
      NIX=NX(KR)
      DO 15 J=1,NIX
15    VMAD(J,KR)=2.0*VMAD(J,KR)-AMT
      RETURN
C
200   FORMAT(///20H0MADELUNG CORRECTION//
     + 19H0RECIPROCAL LATTICE/(6X,3F8.4))
201   FORMAT(7H0RCMIN?,F10.4,10X,5HGMIN?,F10.4,10X,6HRKMAX?,F10.4,
     + 10X,5HTEST?,E12.4/21H SEPARATION CONSTANT?,E12.4)
202   FORMAT(21H0REAL SPACE SUMMATION,11X,4HITR?,I3)
203   FORMAT(17H VMM (HARTREES) ?,5E12.4)
204   FORMAT(27H0RECIPROCAL SPACE SUMMATION,5X,4HITG?,I3)
205   FORMAT(26H0MADELUNG MUFFIN-TIN ZERO?,5E12.4)
C
      END
