      SUBROUTINE MTZ(SIG,RHO,RX,NGRID,RMT,NRR,NX,NR,
     + RC,RK,N,VHAR,VEX,ALPHA,AV,NH)
      DIMENSION SIG(NGRID,NR),RHO(NGRID,NR),RX(NGRID),RMT(NR),
     + NRR(NR),NX(NR),VG(20),RC(3,3),RK(3,N)
      COMMON /WK/ X(3),RB(3)
      DATA PI,NG/3.14159265358,20/
C  GRID REFERENCE FOR RADIUS ON LOUCKS' MESH
      INDEX(y)=20.0*(ALOG(y)+8.8)+1.0
      RAD(A1,A2,A3)=SQRT(A1*A1+A2*A2+A3*A3)
C  SUBROUTINE FOR CALCULATION OF THE MUFFIN-TIN ZERO LEVEL?
C  THE AVERAGE VALUE OF THE POTENTIAL BETWEEN THE MUFFIN-TIN
C  SPHERES IN THE UNIT CELL
C
      PD=6.0/PI/PI
      DO 12 IG=1,NG
12    VG(IG)=0.0
      IG=0
      VHAR=0.0
      VEX=0.0
      NPOINT=0
      NINT=0
      DH=1.0/FLOAT(NH)
1     AH=DH/2.0
      AX=-AH
      DO 7 IX=1,NH
      AX=AX+DH
      AY=-AH
      DO 7 IY=1,NH
      AY=AY+DH
      AZ=-AH
      DO 7 IZ=1,NH
      AZ=AZ+DH
      DO 2 I=1,3
2     X(I)=AX*RC(I,1)+AY*RC(I,2)+AZ*RC(I,3)
      NPOINT=NPOINT+1
C  GIVES SAMPLE POINT X INSIDE THE UNIT CELL - TEST WHETHER
C  INTERSTITIAL
      BX=-1.0
      DO 4 JX=1,2
      BX=BX+1.0
      BY=-1.0
      DO 4 JY=1,2
      BY=BY+1.0
      BZ=-1.0
      DO 4 JZ=1,2
      BZ=BZ+1.0
      DO 3 I=1,3
3     RB(I)=X(I)-BX*RC(I,1)-BY*RC(I,2)-BZ*RC(I,3)
      I=0
      DO 4 IR=1,NR
      INR=NRR(IR)
      DO 4 IIR=1,INR
      I=I+1
      XR=RAD(RB(1)-RK(1,I),RB(2)-RK(2,I),RB(3)-RK(3,I))
      IF(XR.LT.RMT(IR))GOTO 7
4     CONTINUE
C  WE HAVE AN INTERSTITIAL POINT
      NINT=NINT+1
C  SUM COULOMB AND EXCHANGE ENERGIES FROM ATOMS WITHIN 2 UNIT
C  CELLS AROUND THIS POINT
      SUMC=0.0
      SUME=0.0
      BX=-3.0
      DO 6 JX=1,5
      BX=BX+1.0
      BY=-3.0
      DO 6 JY=1,5
      BY=BY+1.0
      BZ=-3.0
      DO 6 JZ=1,5
      BZ=BZ+1.0
      DO 5 I=1,3
5     RB(I)=BX*RC(I,1)+BY*RC(I,2)+BZ*RC(I,3)-X(I)
      J=0
      DO 6 JR=1,NR
      JNR=NRR(JR)
      DO 6 JJR=1,JNR
      J=J+1
      XR=RAD(RB(1)+RK(1,J),RB(2)+RK(2,J),RB(3)+RK(3,J))
      J2=INDEX(XR)
      IF(J2.GE.NX(JR))GOTO 6
      J1=J2-1
      J3=J2+1
      X1=RX(J1)
      X2=RX(J2)
      X3=RX(J3)
      TERMC=(XR-X2)*(XR-X3)/(X1-X2)/(X1-X3)*SIG(J1,JR)
     1     +(XR-X1)*(XR-X3)/(X2-X1)/(X2-X3)*SIG(J2,JR)
     1     +(XR-X2)*(XR-X1)/(X3-X2)/(X3-X1)*SIG(J3,JR)
      TERME=(XR-X2)*(XR-X3)/(X1-X2)/(X1-X3)*RHO(J1,JR)
     1     +(XR-X1)*(XR-X3)/(X2-X1)/(X2-X3)*RHO(J2,JR)
     1     +(XR-X2)*(XR-X1)/(X3-X2)/(X3-X1)*RHO(J3,JR)
      SUMC=SUMC+TERMC
      SUME=SUME+TERME
6     CONTINUE
C
      IF(SUME.LE.1.E-8) THEN
	SUME=.0
      ELSE
	SUME=-1.5*ALPHA*(PD*SUME)**(1./3.)
      ENDIF
      VHAR=VHAR+SUMC
      VEX=VEX+SUME
      JG=MOD(IG,20)+1
      VG(JG)=VG(JG)+SUMC+SUME
      IG=IG+1
7     CONTINUE
      DH=DH/2.0
      NH=NH+NH
      IF(NINT.EQ.0)GOTO 1
C
      ANT=FLOAT(NINT)
      VHAR=VHAR/ANT
      VEX=VEX/ANT
      VINT=VHAR+VEX
C  ESTIMATE STANDARD DEVIATION
      IF(NINT.LT.NG)NG=NINT
      NAG=NINT/NG
      AG=FLOAT(NAG)
      DO 10 IG=1,NG
10    VG(IG)=VG(IG)/AG
      VAR=0.0
      DO 11 IG=1,NG
11    VAR=VAR+(VINT-VG(IG))**2
      VAR=SQRT(VAR/FLOAT(NG*(NG-1)))
C  THE CURRENT MONTE-CARLO VOLUME FOR THE INTERSTITIAL REGION
C  IS VOLC
      VOLC=ANT/FLOAT(NPOINT)*AV
C  VOLT IS THE TRUE VOLUME OF THE REGION BETWEEN MUFFIN-TIN
C  SPHERES IN THE UNIT CELL
      VM=0.0
      DO 8 IR=1,NR
8     VM=VM+FLOAT(NRR(IR))*RMT(IR)**3
      VOLT=AV-4.0*PI*VM/3.0
C
      WRITE(11,200)NINT,NPOINT,NG,NAG,VOLT,VOLC
      WRITE(11,201)VHAR,VEX,VINT,VAR
C
      RETURN
200   FORMAT(///43H0MUFFIN-TIN ZERO CALCULATION, SAMPLING WITH,I6,
     + 20H POINTS FROM GRID OF,I6/24H VARIANCE ESTIMATED FROM,
     + I4,10H GROUPS OF,I5//36H TRUE VOLUME OF INTERSTITIAL REGION?,
     + F11.4,5X,19HMONTE-CARLO VOLUME?,11X,F9.4)
201   FORMAT(27H AVERAGE HARTREE POTENTIAL?,6X,F14.5,5X,
     + 27HAVERAGE EXCHANGE POTENTIAL?,F12.5/
     + 17H0MUFFIN-TIN ZERO?,F12.5,10X,19HSTANDARD DEVIATION?,F12.5)
      END
