      SUBROUTINE MTZM(VH,VS,RX,NGRID,RMT,RWS,JRMT,JRWS,VHAR,VEX)
      DIMENSION VH(NGRID),VS(NGRID),RX(NGRID)
      DOUBLE PRECISION SUMH,SUME
C  SUBROUTINE FOR CALCULATION OF THE MUFFIN-TIN ZERO LEVEL FOR
C  MONOATOMIC CRYSTALS, USING A SPHERICAL AVERAGE OF THE POTENTIAL
C  BETWEEN MUFFIN-TIN RADIUS AND WIGNER-SEITZ RADIUS, AS IN EQ 3.31
C  OF LOUCKS, TRANSFORMED TO THE EXPONENTIAL GRID RX?
C                       RX(I)=EXP(-8.8+0.05(I-1))
C  INTEGRATION BY TRAPEZIUM RULE.  JRMT,JRWS ARE GRID POINTS OUTSIDE
C  MUFFIN-TIN RADIUS AND WIGNER-SEITZ RADIUS RESPECTIVELY
      DX=0.05
      DDX=0.5*DX
      DXX=EXP(3.*DX)
      X=ALOG(RX(JRMT)/RMT)
      RDX=X/DX
      XX=RX(JRMT-1)**3
      XXMT=XX*DXX
      SUMH=0.5*X*(RDX*XX*VH(JRMT-1)+(2.-RDX)*XXMT*VH(JRMT))
      SUME=0.5*X*(RDX*XX*VS(JRMT-1)+(2.-RDX)*XXMT*VS(JRMT))
      XX=XXMT
      JRW=JRWS-1
      IF(JRMT.EQ.JRW)GOTO 2
      VH1=DDX*XX*VH(JRMT)
      VX1=DDX*XX*VS(JRMT)
      JRM=JRMT+1
      DO 1 J=JRM,JRW
      XX=XX*DXX
      VH2=DDX*XX*VH(J)
      VX2=DDX*XX*VS(J)
      SUMH=SUMH+VH1+VH2
      SUME=SUME+VX1+VX2
      VH1=VH2
1     VX1=VX2
2     X=ALOG(RWS/RX(JRW))
      RDX=X/DX
      XXWS=XX*DXX
      SUMH=SUMH+0.5*X*((2.-RDX)*XX*VH(JRW)+RDX*XXWS*VH(JRWS))
      SUME=SUME+0.5*X*((2.-RDX)*XX*VS(JRW)+RDX*XXWS*VS(JRWS))
      C=3./(RWS*RWS*RWS-RMT*RMT*RMT)
      VHAR=C*SUMH
      VEX=C*SUME
      VINT=VHAR+VEX
      WRITE(11,200)VHAR,VEX,VINT
      RETURN
C
200   FORMAT(///37H0MUFFIN-TIN ZERO BY SPHERICAL AVERAGE,/
     + 27H AVERAGE HARTREE POTENTIAL?,6X,F14.5,5X,
     + 27HAVERAGE EXCHANGE POTENTIAL?,F12.5,/
     + 17H0MUFFIN-TIN ZERO?,F12.5)
      END
