      SUBROUTINE NBR(IA,NA,AD,NCON,NRR,NR,RC,RK,N,RMAX,MC)
      DIMENSION IA(MC,NR),NA(MC,NR),AD(MC,NR),NCON(NR),NRR(NR),
     + RC(3,3),RK(3,N)
      COMMON /WK/ RJ(3)
      RAD(A1,A2,A3)=SQRT(A1*A1+A2*A2+A3*A3)
C  ROUTINE TO SUPPLY NEAREST NEIGHBOUR DATA FOR ATOMS IN
C  A CRYSTAL STRUCTURE, GIVEN?
C  RC(I,J)? THE I'TH COORDINATE OF THE J'TH AXIS OF THE UNIT CELL
C  RK(I,J)? THE I'TH COORDINATE OF THE J'TH ATOM IN THE UNIT CELL
C  NRR(IR)? THE NUMBER OF TYPE-IR ATOMS IN THE UNIT CELL
C  THE INFORMATION RETURNED, FOR A TYPE-IR ATOM, IS
C  NCON(IR)? THE NUMBER OF NEAREST NEIGHBOUR SHELLS OF A TYPE-IR
C  ATOM INCLUDED, OUT TO A DISTANCE OF RMAX, BUT .LE. MC
C  IA(J,IR)? THE TYPE OF ATOMS IN THE J'TH NEIGHBOURING SHELL
C  NA(J,IR)? THE NUMBER OF ATOMS IN THE J'TH SHELL
C  AD(J,IR)? THE RADIUS OF THE J'TH SHELL
C  INITIALISATION
      RCMIN=1.0E6
      DO 1 I=1,3
1     RCMIN=AMIN1(RCMIN,RAD(RC(1,I),RC(2,I),RC(3,I)))
      DO 2 IR=1,NR
      DO 2 IC=1,MC
      IA(IC,IR)=0
      NA(IC,IR)=0
2     AD(IC,IR)=1.0E6
C  SEARCH OVER ADJACENT UNIT CELLS TO INCLUDE MC NEAREST NEIGHBOURS
      ITC=IFIX(RMAX/RCMIN)+1
      LIMC=ITC+ITC+1
      AS=-FLOAT(ITC+1)
      AX=AS
      DO 10 JX=1,LIMC
      AX=AX+1.0
      AY=AS
      DO 10 JY=1,LIMC
      AY=AY+1.0
      AZ=AS
      DO 10 JZ=1,LIMC
      AZ=AZ+1.0
      DO 3 J=1,3
3     RJ(J)=AX*RC(J,1)+AY*RC(J,2)+AZ*RC(J,3)
C  RJ IS CURRENT UNIT CELL ORIGIN.  FOR EACH ATOM IN THIS UNIT CELL
C  FIND DISPLACEMENT R FROM KR-TYPE ATOM IN BASIC UNIT CELL
      J=0
      DO 10 JR=1,NR
      JNR=NRR(JR)
      DO 10 JJR=1,JNR
      J=J+1
      K=1
      DO 9 KR=1,NR
      R=RAD(RJ(1)+RK(1,J)-RK(1,K),RJ(2)+RK(2,J)-RK(2,K),
     + RJ(3)+RK(3,J)-RK(3,K))
      IF(R.GT.RMAX)GOTO 9
C  COMPARE R WITH NEAREST NEIGHBOUR DISTANCES ALREADY FOUND
      IC=0
4     IC=IC+1
      IF(IC.GT.MC)GOTO 9
      DR=R-AD(IC,KR)
      IF(ABS(DR).LT.1.0E-4)DR=0.0
      IF(DR)6,5,4
5     IF(IA(IC,KR).NE.JR)GOTO 4
      NA(IC,KR)=NA(IC,KR)+1
      GOTO 9
6     IF(IC.EQ.MC)GOTO 8
      IIC=IC+1
      DO 7 JJC=IIC,MC
      JC=MC+IIC-JJC
      IA(JC,KR)=IA(JC-1,KR)
      NA(JC,KR)=NA(JC-1,KR)
7     AD(JC,KR)=AD(JC-1,KR)
8     IA(IC,KR)=JR
      NA(IC,KR)=1
      AD(IC,KR)=R
9     K=K+NRR(KR)
10     CONTINUE
      DO 12 IR=1,NR
      NCON(IR)=0
      DO 11 IC=1,MC
      IF(NA(IC,IR).EQ.0)GOTO 12
11    NCON(IR)=NCON(IR)+1
12    CONTINUE
      RETURN
      END
