      SUBROUTINE SUMAX(ACC,CHI,RX,NX,NCON,IA,NA,AD,IMAX,NGRID,NR)
      DIMENSION ACC(NGRID),CHI(NGRID,NR),RX(NGRID),NX(NR),
     + IA(NCON),NA(NCON),AD(NCON)
      DOUBLE PRECISION SUM
C  ROUTINE TO PERFORM THE SUMMATION OF CONTRIBUTIONS FROM
C  NEIGHBOURING ATOMS (EQ. 3.22,3.26,3.28).  INTEGRATION BY
C  TRAPEZIUM RULE ON RADIAL GRID  RX(I)=EXP(-8.8+0.05(I-1))
      INDEX(X)=20.*(ALOG(X)+8.8)+2.
      DX=0.05
      DDX=0.5*DX
      DXX=EXP(2.*DX)
      IC=IA(1)
      DO 1 I=1,IMAX
1     ACC(I)=CHI(I,IC)
      DO 4 JA=2,NCON
      IC=IA(JA)
      NIX=NX(IC)
      DO 4 I=1,IMAX
      SUM=0.0D0
      X1=ABS(RX(I)-AD(JA))
      IX1=INDEX(X1)
      IF(IX1.GT.NIX)GOTO 4
      DX1=ALOG(RX(IX1)/X1)
      RDX1=DX1/DX
      X2=AMIN1((RX(I)+AD(JA)),RX(NIX))
      IX2=MIN0(INDEX(X2),NIX)
      DX2=ALOG(RX(IX2)/X2)
      RDX2=DX2/DX
      XX=RX(IX2-1)**2
      XX1=XX*DXX
      IF(IX1.EQ.IX2)GOTO 3
      SUM=SUM+0.5*DX2*((2.-RDX2)*XX*CHI(IX2-1,IC)+
     + RDX2*XX1*CHI(IX2,IC))
      XX=RX(IX1-1)**2
      XX1=XX*DXX
      SUM=SUM+0.5*DX1*(RDX1*XX*CHI(IX1-1,IC)+
     + (2.-RDX1)*XX1*CHI(IX1,IC))
      IX1=IX1+1
      IF(IX1.EQ.IX2)GOTO 4
      XX=XX1
      T1=DDX*XX*CHI(IX1,IC)
      IX2=IX2-1
      DO 2 IX=IX1,IX2
      XX=XX*DXX
      T2=DDX*XX*CHI(IX,IC)
      SUM=SUM+T1+T2
2     T1=T2
      GOTO 4
3     SUM=0.5*(DX2-DX1)*((RDX1+RDX2)*XX*CHI(IX1-1,IC)+
     + (2.-RDX1-RDX2)*XX1*CHI(IX1,IC))
4     ACC(I)=ACC(I)+0.5*SUM*FLOAT(NA(JA))/(AD(JA)*RX(I))
      RETURN
      END

